#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
server:
  port: 0
name: ${symbol_dollar}{spring.application.name:${capitalizedNameOfModuleWithoutType.toLowerCase()}-${typeAsInSourceProcessorOrSink.toLowerCase()}}
spring:
  cloud:
    stream:
      bindings:
#if("Sink" == "${typeAsInSourceProcessorOrSink}" || "Processor" == "${typeAsInSourceProcessorOrSink}")
        input: ${symbol_dollar}name
#end
#if("Source" == "${typeAsInSourceProcessorOrSink}")
        output: ${symbol_dollar}name
#end
#if("Processor" == "${typeAsInSourceProcessorOrSink}")
        output: ${symbol_dollar}name.out
#end